root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -tags dev,mysql,custom -o ./tmp/main ./cmd/http-server"
bin = "tmp/main"
include_ext = ["go", "templ"]
exclude_dir = ["assets", "tmp", "vendor"]
exclude_regex = ["_templ\\.go$"] 
