services:
  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    env_file:
      - .env
    volumes:
      - ./.redis-data:/data

  web:
    build: .
    command: air -c .air/.air.toml
    ports:
      - 40169:40169
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - AIR_FORCE_BUILD=true

  worker:
    build: .
    command: air -c .air/.worker.air.toml
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - AIR_FORCE_BUILD=true

  scheduler:
    build: .
    command: go run -tags=dev cmd/scheduler/main.go
    env_file:
      - .env
    volumes:
      - .:/app

