name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build CLI
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o mirante-linux-amd64 ./cmd/cli/main.go
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o mirante-linux-arm64 ./cmd/cli/main.go
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o mirante-darwin-amd64 ./cmd/cli/main.go
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o mirante-darwin-arm64 ./cmd/cli/main.go
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o mirante-windows-amd64.exe ./cmd/cli/main.go

        chmod +x mirante-*

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          mirante-linux-amd64
          mirante-linux-arm64
          mirante-darwin-amd64
          mirante-darwin-arm64
          mirante-windows-amd64.exe
        generate_release_notes: true
        draft: false
        prerelease: false
        token: ${{ secrets.RELEASE_TOKEN }}